// Numeric limits and defaults for chatGPTWeb/API server timeouts, token
// lengths, and conversation polling. Pure constants — no imports.

export const CHATGPT_WEB_DEFAULT_MODEL_KEY = 'chatgptWeb55Thinking'
export const CHATGPT_WEB_DEFAULT_MODEL_SLUG = 'gpt-5-5-thinking'
export const CHATGPT_WEB_DEFAULT_THINKING_EFFORT = 'extended'
export const CHATGPT_WEB_DEBUG_LOG_KEY = 'chatgptWebDebugLog'
export const MAX_RESPONSE_TOKEN_LENGTH_LIMIT = 256000
export const MAX_CONVERSATION_CONTEXT_LENGTH_LIMIT = 200
export const DEFAULT_MAX_RESPONSE_TOKEN_LENGTH = 2000
export const DEFAULT_CHATGPT_WEB_CONVERSATION_POLL_TIMEOUT_SECONDS = 2700
export const MIN_CHATGPT_WEB_CONVERSATION_POLL_TIMEOUT_SECONDS = 30
export const MAX_CHATGPT_WEB_CONVERSATION_POLL_TIMEOUT_SECONDS = 7200
export const DEFAULT_CHATGPT_WEB_CONVERSATION_POLL_INTERVAL_SECONDS = 10
export const MIN_CHATGPT_WEB_CONVERSATION_POLL_INTERVAL_SECONDS = 1
export const MAX_CHATGPT_WEB_CONVERSATION_POLL_INTERVAL_SECONDS = 300
export const DEFAULT_CHATGPT_WEB_HISTORY_SYNC_RPM = 6
export const MIN_CHATGPT_WEB_HISTORY_SYNC_RPM = 1
export const MAX_CHATGPT_WEB_HISTORY_SYNC_RPM = 30
export const DEFAULT_CHATGPT_WEB_HISTORY_SYNC_INTERVAL_HOURS = 12
export const MIN_CHATGPT_WEB_HISTORY_SYNC_INTERVAL_HOURS = 1
export const MAX_CHATGPT_WEB_HISTORY_SYNC_INTERVAL_HOURS = 168
export const DEFAULT_API_SERVER_REQUEST_TIMEOUT_SECONDS = 180
export const MIN_API_SERVER_REQUEST_TIMEOUT_SECONDS = 30
export const MAX_API_SERVER_REQUEST_TIMEOUT_SECONDS = 3600
export const DEFAULT_API_SERVER_THINKING_TIMEOUT_SECONDS = 2700
export const MIN_API_SERVER_THINKING_TIMEOUT_SECONDS = 30
export const MAX_API_SERVER_THINKING_TIMEOUT_SECONDS = 7200
